spring.application.name=19_UY_CHAKRIYA_SR_Web_Homework002
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_homework2
spring.datasource.username=postgres
spring.datasource.password=123456